### PR TITLE
Add support for listing and loading profiles

### PR DESCRIPTION
**Pull request by sparten11740**
Hey there, 

as mentioned in [this issue](https://github.com/diogotr7/OpenRGB.NET/issues/9), the SDK now supports profile management. This pull request adds support for listing all available profiles on the server and load a profile by its name. I don't have much of a use case for saving profiles via the SDK myself, so I left that part out.

Hope this works for you.

### CODE REVIEW

**Comment by wojciech-Kokot** [comment]
is it possible make nudget or new version of dll I'm using powershell to manage devices I do not have visual studio to compile it.

**Comment by diogotr7** [comment]
I looked into this and found something i think is a bug. Blocked by https://gitlab.com/CalcProgrammer1/OpenRGB/-/merge_requests/353

**Comment by sparten11740** [comment]
I noticed that as well when I used your helper method and the 'p' was cutoff from the profile extension. Definitely makes sense to fix that upstream.

Edit: The upstream fix is merged, I added another commit that uses your helper method to unmarshal the profile names.

**Comment by diogotr7** [comment]
Awesome, that's exactly what the helper method is for. 

Thanks for contributing, i'll add the other profile related commands myself.

**Pull request merged**
